SELECT
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1059) AND D.RIND IN ('01')  THEN CIS2.NVAL(D.COL3) ELSE 0 END))||' <> '||
  (CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1059) AND D.RIND IN ('01')  THEN CIS2.NVAL(D.COL4) ELSE 0 END)) +
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1058) AND D.RIND IN ('10','20') THEN CIS2.NVAL(D.COL17) ELSE 0 END)))  
  
  AS REZULTAT
  
FROM CIS2.VW_DATA_ALL_TEMP D

WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
   (:CAPITOL = :CAPITOL           OR :CAPITOL <>  :CAPITOL) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (50)  AND
  D.CAPITOL IN (1058,1059)  
  
HAVING
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1059) AND D.RIND IN ('01')  THEN CIS2.NVAL(D.COL3) ELSE 0 END))  <> 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1059) AND D.RIND IN ('01')  THEN CIS2.NVAL(D.COL4) ELSE 0 END)) +
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1058) AND D.RIND IN ('10','20') THEN CIS2.NVAL(D.COL17) ELSE 0 END)) 