INSERT INTO CIS2.MD_RIND (
    ID_MD,
    FORM,
    FORM_VERS,
    CAPITOL,
    CAPITOL_VERS,
    RIND,
    RIND_VERS,
    DENUMIRE,
    DECIMAL_POS,
    COL_ACTIV,
    ORDINE,
    DATA_REG,
    STATUT,
    DINAMIC
)
SELECT
    ID_MD,
    FORM,
    FORM_VERS,
    CAPITOL,
    CAPITOL_VERS,
    '4' || SUBSTR(RIND, 2) AS RIND,
    RIND_VERS,
    DENUMIRE,
    DECIMAL_POS,
    COL_ACTIV,
    4000 + ROW_NUMBER() OVER (ORDER BY ORDINE) AS ORDINE,
    SYSDATE AS DATA_REG,
    STATUT,
    DINAMIC
FROM CIS2.MD_RIND
WHERE FORM = 50
  AND CAPITOL = 1058
  AND CAPITOL_VERS = 2015
  AND STATUT = '1'
  AND RIND LIKE '3%'
  AND LENGTH(RIND) > 3;