
-- Adauga partea de insert in CIS2.MD_RIND
SELECT
    ID_MD,
    FORM,
    FORM_VERS,
    CAPITOL,
    CAPITOL_VERS,
    RIND,
    '4' || SUBSTR(RIND, 2) AS RIND_MODIFICAT,
    RIND_VERS,
    DENUMIRE,
    DECIMAL_POS,
    COL_ACTIV,
    4000 + ROWNUM ORDINE,
    SYSDATE DATA_REG,
    STATUT,
    DINAMIC
FROM CIS2.MD_RIND
WHERE FORM = 50
  AND CAPITOL = 1058
  AND CAPITOL_VERS = 2015
  AND STATUT = '1'
  AND RIND LIKE '3%'
  AND LENGTH(RIND) > 3
ORDER BY ORDINE;