--INSERT INTO CIS2.MD_RIND (
--    ID_MD,
--    FORM,
--    FORM_VERS,
--    CAPITOL,
--    CAPITOL_VERS,
--    RIND,
--    RIND_VERS,
--    DENUMIRE,
--    DECIMAL_POS,
--    COL_ACTIV,
--    ORDINE,
--    DATA_REG,
--    STATUT,
--    DINAMIC
--)

SELECT
ROWNUM ID_MD,
50 FORM,
2000 FORM_VERS,
1058 CAPITOL,
2015 CAPITOL_VERS,
ITEM_CODE RIND,
2015 RIND_VERS, 
NAME DENUMIRE,
'00000000000000000' DECIMAL_POS,
'11111111111111111' COL_ACTIV,
ROWNUM + 5002 ORDINE,
   SYSDATE AS DATA_REG,
    '1' STATUT,
    '1' DINAMIC
FROM

(
SELECT 
ITEM_CODE,
NAME,
SHOW_ORDER 
FROM CIS2.VW_CLS_CLASS_ITEM
WHERE
CLASS_CODE IN ('SPEC_3EDU')
AND A01 = '6'
ORDER BY 
SHOW_ORDER
)